### ISSUE TITLE
Refactor HIR places

### ISSUE THREAD

**Issue by arora-aman** [sexxi-goose/rust#14]
Discussion: https://rust-lang.zulipchat.com/#narrow/stream/189812-t-compiler.2Fwg-rfc-2229/topic/refactoring.20.60hir.3A.3APlace.60.20and.20.60hir_id.60

- [x] Investigate usage of usage of `hir_id` of `hir::Place` and confirm it is only being used for error reporting.

The current suggestion is to
- [ ] Refactor code and rename `Place` to `PlaceReference`
- [ ] Reintroduce `Place` except `hir_id` and `span` are not part of `Place` anymore
- [ ] Modify `PlaceReference` so it looks something like this:
```rust
struct PlaceReference {
    hir_id: HirId,
    span: Span,
    place: Place,
}
```
- [ ] Replace `PlaceReference` to `Place` if it does not need `hir_id` and `span`

[Place documentation](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/expr_use_visitor/struct.Place.html)

**Comment by roxelo** [comment]
The current suggestion is to

- [x] Refactor code and rename `Place` to `PlaceReference`
- [x] Reintroduce `Place` except `hir_id` and `span` are not part of `Place` anymore
- [ ] Modify `PlaceReference` so it looks something like this:
```rust
struct PlaceReference {
    hir_id: HirId,
    span: Span,
    place: Place,
}
```
- [ ] Replace `PlaceReference` to `Place` if it does not need `hir_id` and `span`

[Place documentation](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/expr_use_visitor/struct.Place.html)

First step is to look at the usage of `hir_id` of `hir::Place` and confirm it is only being used for error reporting.

**Comment by arora-aman** [comment]
Within `librustc_typchk`, HirPlace is referred as `mc::Place` outside it is referred toi as `rustc_typeck::expr_use_visitor::Place`.

Easiest way I could think of was to check for files where `expr_use_visitor::Place` was being included.


1) `rg "expr_use.*\*"`,  Search for patterns like `"expr_use<anything>*` to match for an include all from expr_use_visitor, returned nothing.
2) `rg "\bexpr.*\bPlace\b"`. `\b` is used to mark a word boundry. So this will allow patterns like `expr_use_visitior::Place` but not `someexprPlace`. The intent was to search for lines like `expr_use_visitor{Place`

Removing results from within `typchk` and some extra unintended matches we have:

```
librustc_mir_build/build/expr/as_place.rs
69:    crate fn as_place<M>(&mut self, mut block: BasicBlock, expr: M) -> BlockAnd<Place<'tcx>>

librustc_mir_build/build/expr/into.rs
398:                debug_assert!(Category::of(&expr.kind) == Some(Category::Place));
406:                debug_assert!(Category::of(&expr.kind) == Some(Category::Place));
415:                debug_assert!(Category::of(&expr.kind) == Some(Category::Place));

tools/clippy/clippy_lints/src/escape.rs
9:use rustc_typeck::expr_use_visitor::{ConsumeMode, Delegate, ExprUseVisitor, Place, PlaceBase};

tools/clippy/clippy_lints/src/loops.rs
31:use rustc_typeck::expr_use_visitor::{ConsumeMode, Delegate, ExprUseVisitor, Place, PlaceBase};

tools/clippy/clippy_lints/src/utils/usage.rs
11:use rustc_typeck::expr_use_visitor::{ConsumeMode, Delegate, ExprUseVisitor, Place, PlaceBase};
```

MIR relies on `hir::Expr`  for lowering and not `HirPlace` (thanks to Matthew Jaspeer) so we are left with 
```

tools/clippy/clippy_lints/src/escape.rs
9:use rustc_typeck::expr_use_visitor::{ConsumeMode, Delegate, ExprUseVisitor, Place, PlaceBase};

tools/clippy/clippy_lints/src/loops.rs
31:use rustc_typeck::expr_use_visitor::{ConsumeMode, Delegate, ExprUseVisitor, Place, PlaceBase};

tools/clippy/clippy_lints/src/utils/usage.rs
11:use rustc_typeck::expr_use_visitor::{ConsumeMode, Delegate, ExprUseVisitor, Place, PlaceBase};
```

More info on `ripgrep`/`rg`: https://github.com/sexxi-goose/internal_fydp_documentation/wiki/Dev-Setup#searching-the-codebase
