### ISSUE TITLE
Update Typchk memory categorization

### ISSUE THREAD

**Issue by arora-aman** [sexxi-goose/rust#7]
Executes during typeck, so the tables are accessed differently, but still probably should be updated to use `closure_captures`.

**Comment by arora-aman** [comment]
Similar to #6

**Comment by arora-aman** [comment]
`librustc_typeck/mem_categorization`

**Comment by arora-aman** [comment]
This is what generates Places that we will be capturing going on.

From what I can understand we need to make projections contain how to access the member here: https://github.com/sexxi-goose/rust/blob/master/src/librustc_typeck/mem_categorization.rs#L486

```rust 
let ret = Place {
            hir_id,
            span,
            ty: var_ty,
            base: PlaceBase::Upvar(upvar_id),
            projections: Vec::new(), // This probably needs fixing
        };
```

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/expr_use_visitor/struct.Place.html#structfield.projections

**Comment by roxelo** [comment]
Blocked on #14

**Comment by jenniferwills** [comment]
> Blocked on #14

is this still blocked @arora-aman @roxelo? #14 is merged and closed
