### ISSUE TITLE
Compute the upvar list in Typecheck

### ISSUE THREAD

**Issue by arora-aman** [sexxi-goose/rust#9]
Refactor UpvarListMap to use HIR places: `librustc_middle/ty/mod.rs` and compute the the list in 
`librustc_typeck/check/upvar.rs`

**Comment by arora-aman** [comment]
- https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/expr_use_visitor/struct.Place.html
- https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/check/upvar/index.html

**Comment by arora-aman** [comment]
Goes with #10

**Comment by arora-aman** [comment]
We might need to refactor HIR Places to remove `hir_id` or make it consistent. 

With the current setup, if you have || use(x.foo, x.foo), then the Place for x.foo would be different depending on which x.foo it was (each has a distinct id in the tree)

**Comment by roxelo** [comment]
Blocked on #14
